# name: ETL pipline demo

# on:
#   push:
#     branches:
#     - main
# jobs:
#   extract-data:
#            runs-on: ubuntu-latest
#            steps:
           
#             - name: checkout code
#               uses: actions/checkout@v2

#             - name: run extract.py
#               run: python extract.py

#   transform-data:
#             runs-on: ubuntu-latest
#             needs: extract-data

#             steps:

#             - name: checkout code
#               uses: actions/checkout@v2

#             - name: run transform.py
#               run: python transform.py

#   load-data:
#             runs-on: ubuntu-latest
#             needs: transform-data
#             steps:

#             - name: checkout code
#               uses: actions/checkout@v2

#             - name: run load.py
#               run: python load.py  


name: github action demo pipline

on:
  push:
    branches:
    - main

jobs:
  extract-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v2

      - name: show python version
        run: python --version

      - name: set up python
        uses: action/setup-ython@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: pip install -r requirements.txt

      - name: run extract.py
        run: python extract.py 